# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'

pod'AFNetworking'
pod'SDWebImage' 
pod'JSONModel'
pod 'SVProgressHUD'
pod'Masonry'
pod 'BRPickerView'
pod 'Bytedance-UnionAD'

target 'accountProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for accountProject

  target 'accountProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'accountProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
